
library(tidyverse)

# download GDAL
source_url <- "https://download.osgeo.org/gdal/3.7.0/gdal-3.7.0.tar.gz"
if (!file.exists("data-raw/gdal-3.7.0")) {
  curl::curl_download(source_url, "data-raw/gdal-source.tar.gz")
  untar("data-raw/gdal-source.tar.gz", exdir = "data-raw")
}

# make sure the dir exists
gdal_dir <- list.files("data-raw", "^gdal-[0-9.]+", include.dirs = TRUE, full.names = TRUE)
print(gdal_dir)
stopifnot(dir.exists(gdal_dir), length(gdal_dir) == 1)
#src_dir <- file.path(gdal_dir, "src")
src_dir <- file.path(gdal_dir, "gcore")

# run cmake and find which source folders to scan
build_dir <- file.path(gdal_dir, "build_for_cmake")
dir.create(build_dir)
# withr::with_dir(
#    build_dir,
#    system("cmake ..")
#    )
cmake_dirs <- fs::dir_ls(build_dir, recurse = TRUE, type = "d")
hh <- fs::dir_ls(gdal_dir, regexp = "\\.(h|hpp)$", recurse = TRUE)
#hh <- hh[dirname(hh) %in% gsub("build_for_cmake/", "", cmake_dirs)]

cc <- fs::dir_ls(gdal_dir, regexp = "\\.cpp$", recurse = TRUE)
cc <- cc[dirname(cc) %in% gsub("build_for_cmake/", "", cmake_dirs)]

# headers live in src/gdal_include (we don't want them exposed
# for packages LinkingTo)
headers <- tibble(
  path = hh,
  # path = list.files(
  #   file.path(gdal_dir, "gcore"), "\\.(h|inl)$",
  #   full.names = TRUE,
  #   recursive = TRUE
  # ),
  final_path = str_replace(path, ".*?gdal-3.7.0/", "src/gdal/")
)

# source files live in src/gdal
source_files <- tibble(
  #path = list.files(file.path(gdal_dir, "gcore"), "\\.cpp$", full.names = TRUE, recursive = TRUE),
  path = cc,
  final_path = str_replace(path, ".*?gdal-3.7.0/", "src/gdal/")
)

# remove current source and header files
unlink("src/gdal_include/gdal", recursive = TRUE)
#unlink("src/geos_include/ryu", recursive = TRUE)
#unlink("src/geos_include/geos_c.h")
unlink("src/gdal_include", recursive = TRUE)
unlink("src/gdal", recursive = TRUE)
#unlink("src/ryu", recursive = TRUE)

# create destination dirs
dest_dirs <- c(
  headers %>% pull(final_path),
  source_files %>% pull(final_path)
) %>%
  dirname() %>%
  unique() %>%
  sort()
dest_dirs[!dir.exists(dest_dirs)] %>% walk(dir.create, recursive = TRUE)

# copy source files
stopifnot(file.copy(headers$path, headers$final_path))
stopifnot(file.copy(source_files$path, source_files$final_path))
# stopifnot(
#   file.copy(
#     file.path(gdal_dir, os_c.h"),
#     "src/geos_include/geos_c.h"
#   )
# )
# stopifnot(
#   file.copy(
#     file.path(gdal_dir, "capi/geos_ts_c.cpp"),
#     "src/geos/geos_ts_c.cpp"
#   )
# )

# dir.create("src/geos_include/geos/vend")
# stopifnot(
#   file.copy(
#     file.path(gdal_dir, "include/geos/vend/include_nlohmann_json.hpp"),
#     "src/geos_include/geos/vend/include_nlohmann_json.hpp"
#   )
# )
#
# # we need to point this to our own version of nlohmann_json at "nlohmann_json.hpp"
# # which we've modified to pass the cran checks
# usethis::edit_file("src/geos_include/geos/vend/include_nlohmann_json.hpp")
#
# dir.create("src/ryu")
# dir.create("src/geos_include/ryu")
# stopifnot(
#   # need to copy ryu library
#   file.copy(
#     file.path(gdal_dir, "src/deps/ryu/d2s.c"),
#     "src/ryu/d2s.c"
#   ),
#   file.copy(
#     file.path(
#       gdal_dir, "src/deps/ryu",
#       c(
#         "common.h", "d2fixed_full_table.h",
#         "d2s_full_table.h", "d2s_intrinsics.h",
#         "digit_table.h", "ryu.h"
#       )
#     ),
#     "src/geos_include/ryu"
#   )
# )

# need to update objects because we've placed the geos bits in subfolders
objects <- list.files("src", pattern = "\\.c(pp)?$", recursive = TRUE, full.names = TRUE)
# objects <- objects[-grep("gdaldither.cpp", objects)]
# objects <- objects[-grep("gdaltransformer.cpp", objects)]

objects <- objects %>%   gsub("\\.c(pp)?$", ".o", .) %>%
  gsub("src/", "", .) %>%
  paste("    ", ., "\\", collapse = "\n") %>%
  gsub("\\\\\\s*$", "", .)


headpaths <- c("-I../src/gdal", file.path("-I../src/gdal",
                                                       unique(gsub("data-raw/gdal-3.7.0/", "", dirname(hh)))))

writeLines(paste0(paste0("## generated by script, do not modify\nPKG_CPPFLAGS = -I../src/gdal ", paste0(headpaths, collapse = " "), "\nPKG_CXXFLAGS = -I../src/gdal\nCXX_STD = CXX11\n\nOBJECTS =    "),
           objects), "src/Makevars")



# Update OBJECTS in Makevars (copied to clipboard)
#clipr::write_clip(objects)
#usethis::edit_file("src/Makevars")
#usethis::edit_file("src/Makevars.win")

#' Reminders about manual modifications that are needed
#' - noding__snapround__MCIndexSnapRounder.cpp: Replace cerr with cpp_compat_cerr
#usethis::edit_file("src/geos/noding/snapround/MCIndexSnapRounder.cpp")
#' - src/operation__overlay__ElevationMatrix.cpp: Replace cerr with cpp_compat_cerr
#usethis::edit_file("src/geos/operation/overlay/ElevationMatrix.cpp")
#' - src/simplify/TopologyPreservingSimplifier.cpp: Replace cerr with cpp_compat_cerr
#usethis::edit_file("src/geos/simplify/TopologyPreservingSimplifier.cpp")
#' - util/Profiler.cpp: Replace cerr with cpp_compat_cerr
#usethis::edit_file("src/geos/util/Profiler.cpp")
#' - Update exported C API using update-libgeos-api.R
